export const GET_APP_STRINGS_REQUEST = 'GET_APP_STRINGS_REQUEST';
export const GET_APP_STRINGS_SUCCESS = 'GET_APP_STRINGS_SUCCESS';
export const GET_APP_STRINGS_FAIL = 'GET_APP_STRINGS_FAIL';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
