export const GET_APP_STRINGS_REQUEST = 'GET_APP_STRINGS_REQUEST';
export const GET_APP_STRINGS_SUCCESS = 'GET_APP_STRINGS_SUCCESS';
export const GET_APP_STRINGS_FAIL = 'GET_APP_STRINGS_FAIL';

export const CHANGE_APP_LANGUAGE = 'CHANGE_APP_LANGUAGE';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';

//App UI Modal's Actions
export const TOGGLE_LANGUAGE_SELECTION_MODAL =
  'TOGGLE_LANGUAGE_SELECTION_MODAL';

//Flirts and Superflirts list Actions
export const GET_FLIRTS_REQUEST = 'GET_FLIRTS_REQUEST';
export const GET_FLIRTS_SUCCESS = 'GET_FLIRTS_SUCCESS';
export const GET_FLIRTS_FAILED = 'GET_FLIRTS_FAILED';

//Bookmarks list Actions
export const GET_BOOKMARKS_REQUEST = 'GET_BOOKMARKS_REQUEST';
export const GET_BOOKMARKS_SUCCESS = 'GET_BOOKMARKS_SUCCESS';
export const GET_BOOKMARKS_FAILED = 'GET_BOOKMARKS_FAILED';
