export const GET_APP_STRINGS_REQUEST = 'GET_APP_STRINGS_REQUEST';
export const GET_APP_STRINGS_SUCCESS = 'GET_APP_STRINGS_SUCCESS';
export const GET_APP_STRINGS_FAIL = 'GET_APP_STRINGS_FAIL';

export const CHANGE_APP_LANGUAGE = 'CHANGE_APP_LANGUAGE';

export const SET_SELECTED_USER_GENDER = 'SET_SELECTED_USER_GENDER';
export const SET_SELECTED_LOOKING_GENDER = 'SET_SELECTED_LOOKING_GENDER';
export const SET_USER_COUNTRY = 'SET_USER_COUNTRY';

export const SHOW_TOAST = 'SHOW_TOAST';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';

//App UI Modal's Actions
export const TOGGLE_LANGUAGE_SELECTION_MODAL =
  'TOGGLE_LANGUAGE_SELECTION_MODAL';
export const TOGGLE_GALLERY_SWIPER_MODAL =
  'TOGGLE_GALLERY_SWIPER_MODAL';

//Flirts and Proflirts list Actions
export const GET_FLIRTS_REQUEST = 'GET_FLIRTS_REQUEST';
export const GET_FLIRTS_SUCCESS = 'GET_FLIRTS_SUCCESS';
export const GET_FLIRTS_FAILED = 'GET_FLIRTS_FAILED';

//Bookmarks list Actions
export const GET_BOOKMARKS_REQUEST = 'GET_BOOKMARKS_REQUEST';
export const GET_BOOKMARKS_SUCCESS = 'GET_BOOKMARKS_SUCCESS';
export const GET_BOOKMARKS_FAILED = 'GET_BOOKMARKS_FAILED';

// User Profile Details
export const GET_USER_PROFILE_REQUEST = 'GET_USER_PROFILE_REQUEST';
export const GET_USER_PROFILE_SUCCESS = 'GET_USER_PROFILE_SUCCESS';
export const GET_USER_PROFILE_FAIL = 'GET_USER_PROFILE_FAIL';

// User's Chat List
export const GET_USER_CHAT_LIST_REQUEST = 'GET_USER_CHAT_LIST_REQUEST';
export const GET_USER_CHAT_LIST_SUCCESS = 'GET_USER_CHAT_LIST_SUCCESS';
export const GET_USER_CHAT_LIST_FAIL = 'GET_USER_CHAT_LIST_FAIL';

//Get Payment Module
export const GET_PAYMENT_MODULE_REQUEST = 'GET_PAYMENT_MODULE_REQUEST';
export const GET_PAYMENT_MODULE_SUCCESS = 'GET_PAYMENT_MODULE_SUCCESS';
export const GET_PAYMENT_MODULE_FAIL = 'GET_PAYMENT_MODULE_FAIL';

//Get General Settings
export const GET_GENERAL_SETTINGS_SUCCESS = 'GET_GENERAL_SETTINGS_SUCCESS';

//Get Seal Url
export const GET_SEAL_URL_REQUEST = 'GET_SEAL_URL_REQUEST';
export const GET_SEAL_URL_SUCCESS = 'GET_SEAL_URL_SUCCESS';
export const GET_SEAL_URL_FAILED = 'GET_SEAL_URL_FAILED';
