export const APP_STRINGS = {
    find_your_match: "Find your match with our poweful algorithms",
    casual_chating: "Casual chatting and flirting",
    login: "Login",
    register: 'Register',
    email: 'Email',
    email_error_1: 'Please enter email address!',
    email_error_2: 'Invalid email address!',
    password: 'Password',
    confirm_password: 'Confirm Password',
    password_error_1: 'Please enter password!',
    password_error_2: "Password doesn't match!",
    forgot_password: 'Forgot password?',
    or: "or",
    login_with_facebook: "Log in with Facebook",
    login_with_google: "Log in with Google",
    login_with_apple: "Log in with Apple",
    continue_with_facebook: "Continue with Facebook",
    continue_with_google: "Continue with Google",
    continue_with_apple: "Continue with Apple",
    dont_have_an_account: "Don't you have an account?",
    create_one: 'Create One',
    back: "Back",
    forgot_password_title: "Did you forgot your password?",
    forgot_password_description: "Please enter your email address you are using for your account bellow and we will send you a password reset link.",
    request_new_password: "Request New Password",
    back_to_login: "Back to login",
    create_account: "Create account",
    i_am: 'I am',
    next: 'Next',
    user_name: 'Username',
    user_name_error_1: 'Username must not be empty!',
    birthday: "Birthday",
    gender: 'Gender',
    optional: "Optional",
    passions: "Passions",
    add_passions: "Add passions",
    sexual_orientation: "Sexual orientation",
    add_sexual_orientation: "Add sexual orientation",
    continue: "Continue",
    select_profile_picture: "Select profile picture",
    flirts: 'Flirts',
    spotlight: "Spotlight",
    filter_flirt_suggestions: "Filter flirt suggestions",
    i_am_looking_for: "I'm looking for",
    select_gender: "Select gender",
    age_range: "Age Range",
    city: "City",
    max_distance: "Max. distance",
    select_language: "Select language",
    select_orientation: 'Select orientation',
    save: "Save",
    reset_filters: "Reset Filters",
    erotic_image: "Erotic Image",
    only_for_friends: 'Only for friends',
    unlock_for: "Unlock for",
    report: "Report",
    block: "Block",
    interests: "Interests",
    details: "Details",
    dob: "Date of birth",
    friend_request: "Friend request",
    like: "Like",
    kiss: "Kiss",
    sticker: "Sticker",
    cost: "Cost",
    Coins: "Coins",
    send: "Send",
    cancel: "Cancel",
    notifications: "Notifications",
    no_notifications_found: "No notifications found!",
    friend_requests: "Friend requests",
    you_have_sent_friend_request_to: "You have sent friend request to",
    no_chats_found: "No chats found!",
    messages: "Messages",
    type_message: "Type message",
    send_message_for: "Send message for",
    view_profile: "View profile",
    deleteconversation: "Delete Conversation",
    deletealert: "Are you sure you want to delete this?",
    this: "this",
    conversation: "conversation",
    delete: "Delete",
    step: "Step",
    payment_method: "Payment method",
    choose_your_package_size: "Choose your package size",
    own_package: "Own package",
    own_package_description: "How many credits would you like to have? - Here you have it in your own hands!",
    order_now: "Order now",
    no_friends: 'No friends found!',
    kisses: 'Kisses',
    logout: 'Logout',
    profile: "Profile",
    boost: "Boost",
    photos: 'Photos',
    account_info: "Account Info",
    appearance: "Appearance",
    language: "Language",
    privacy_policy: 'Privacy Policy',
    help: "Help",
    support: "Support",
}

const GERMAN_STRINGS = {
    find_your_match: "Finden Sie Ihren Partner mit unseren leistungsstarken Algorithmen",
    casual_chating: "Lässiges Chatten und Flirten",
    login: "Anmeldung",
    register: 'Registrieren',
    email: 'Email',
    email_error_1: 'Bitte E-Mail-Adresse eingeben!',
    email_error_2: 'Ungültige E-Mail-Adresse!',
    password: 'Passwort',
    confirm_password: 'Kennwort bestätigen',
    password_error_1: 'Bitte Passwort eingeben!',
    password_error_2: "Passwort stimmt nicht überein!",
    forgot_password: 'Passwort vergessen?',
    or: "oder",
    login_with_facebook: "Mit Facebook einloggen",
    login_with_google: "Mit Google einloggen",
    login_with_apple: "Mit Apple anmelden",
    continue_with_facebook: "Weiter mit Facebook",
    continue_with_google: "Weiter mit Google",
    continue_with_apple: "Weiter mit Apple",
    dont_have_an_account: "Hast du kein Konto?",
    create_one: 'Erstelle einen',
    back: "Zurück",
    forgot_password_title: "Haben Sie Ihr Passwort vergessen?",
    forgot_password_description: "Bitte geben Sie unten Ihre E-Mail-Adresse ein, die Sie für Ihr Konto verwenden, und wir senden Ihnen einen Link zum Zurücksetzen des Passworts.",
    request_new_password: "Fordere ein neues Passwort an",
    back_to_login: "Zurück zur Anmeldung",
    create_account: "Benutzerkonto erstellen",
    i_am: 'ich bin',
    next: 'Nächster',
    user_name: 'Nutzername',
    user_name_error_1: 'Benutzername darf nicht leer sein!',
    birthday: "Geburtstag",
    gender: 'Geschlecht',
    optional: "Optional",
    passions: "Leidenschaften",
    add_passions: "Leidenschaften hinzufügen",
    sexual_orientation: "Sexuelle Orientierung",
    add_sexual_orientation: "Sexuelle Orientierung hinzufügen",
    continue: "Fortsetzen",
    select_profile_picture: "Profilbild auswählen",
    flirts: 'Flirt',
    spotlight: "Scheinwerfer",
    filter_flirt_suggestions: "Flirtvorschläge filtern",
    i_am_looking_for: "Ich suche",
    select_gender: "Wähle Geschlecht",
    age_range: "Altersspanne",
    city: "Stadt",
    max_distance: "max. Entfernung",
    select_language: "Sprache auswählen",
    select_orientation: 'Ausrichtung auswählen',
    save: "speichern",
    reset_filters: "Filter zurücksetzen",
    erotic_image: "Erotisches Bild",
    only_for_friends: 'Nur für Freunde',
    unlock_for: "Entsperren für",
    report: "Bericht",
    block: "Block",
    interests: "Interessen",
    details: "Einzelheiten",
    dob: "Geburtsdatum",
    friend_request: "Freundschaftsanfrage",
    like: "Mögen",
    kiss: "Kuss",
    sticker: "Aufkleber",
    cost: "Kosten",
    Coins: "Münzen",
    send: "Senden",
    cancel: "Stornieren",
    notifications: "Benachrichtigungen",
    no_notifications_found: "Keine Benachrichtigungen gefunden!",
    friend_requests: "Freundschaftsanfragen",
    you_have_sent_friend_request_to: "Sie haben eine Freundschaftsanfrage gesendet an sent",
    no_chats_found: "Keine Chats gefunden!",
    messages: "Mitteilungen",
    type_message: "Nachricht eingeben",
    send_message_for: "Nachricht senden für",
    view_profile: "Profil anzeigen",
    deleteconversation: "Konversation löschen",
    deletealert: "Möchten Sie dies wirklich löschen?",
    this: "diese",
    conversation: "Konversation",
    delete: "Löschen",
    step: "Schritt",
    payment_method: "Zahlungsmethode",
    choose_your_package_size: "Wählen Sie Ihre Paketgröße",
    own_package: "Eigenes Paket",
    own_package_description: "Wie viele Credits möchten Sie haben? - Hier haben Sie es selbst in der Hand!",
    order_now: "Jetzt bestellen",
    no_friends: 'Keine Freunde gefunden!',
    kisses: 'Küsse',
    logout: 'Ausloggen',
    profile: "Profil",
    boost: "Boost",
    photos: 'Fotos',
    account_info: "Kontoinformation",
    appearance: "Aussehen",
    language: "Sprache",
    privacy_policy: 'Datenschutz-Bestimmungen',
    help: "Hilfe",
    support: "Unterstützung",
    //New labels
    tickets: "Tickets",
    add_new: "Add new",
    no_tickets_found: "No tickets found!",
    delete_account: "Delete Account",
    upload_new: "Upload new",
    select_your_language: "Select your language",
    buy_coins: "Buy coins",
    you_will_be_credited: "You will be credited",
    credits_after_purchase: "credits after purchase",
    online: "Online",
    offline: "Offline",
    are_you_sure_you_want_to_block: "Are you sure you want to block?",
    are_you_sure_you_want_to_logout: "Are you sure you want to logout?",
    verified: "Verified",
    unfriend: "Unfriend",
    start_conversation: "Start Conversation!",
    sorry_but_you_dont_have_enough_coins: "Sorry, but you don’t have enough coins to send this message.",
    buy_coins_now: "Buy coins now",
    see_more: "See more",
    boost_your_profile_and_get_into_spotlight_list_for: "Boost your profile and get into Spotlight list for",
    no_thanks: "No, thanks!",
}