export const APP_STRINGS = {
    find_your_match: "Find your match with our poweful algorithms",
    casual_chating: "Casual chatting and flirting",
    login: "Login",
    register: 'Register',
    email: 'Email',
    email_error_1: 'Please enter email address!',
    email_error_2: 'Invalid email address!',
    password: 'Password',
    confirm_password: 'Confirm Password',
    password_error_1: 'Please enter password!',
    password_error_2: "Password doesn't match!",
    forgot_password: 'Forgot password?',
    or: "or",
    login_with_facebook: "Log in with Facebook",
    login_with_google: "Log in with Google",
    login_with_apple: "Log in with Apple",
    continue_with_facebook: "Continue with Facebook",
    continue_with_google: "Continue with Google",
    continue_with_apple: "Continue with Apple",
    dont_have_an_account: "Don't you have an account?",
    create_one: 'Create One',
    back: "Back",
    forgot_password_title: "Did you forgot your password?",
    forgot_password_description: "Please enter your email address you are using for your account bellow and we will send you a password reset link.",
    request_new_password: "Request New Password",
    back_to_login: "Back to login",
    create_account: "Create account",
    i_am: 'I am',
    next: 'Next',
    user_name: 'Username',
    user_name_error_1: 'Username must not be empty!',
    birthday: "Birthday",
    gender: 'Gender',
    optional: "Optional",
    passions: "Passions",
    add_passions: "Add passions",
    sexual_orientation: "Sexual orientation",
    add_sexual_orientation: "Add sexual orientation",
    continue: "Continue",
    select_profile_picture: "Select profile picture",
    flirts: 'Flirts',
    spotlight: "Spotlight",
    filter_flirt_suggestions: "Filter flirt suggestions",
    i_am_looking_for: "I'm looking for",
    select_gender: "Select gender",
    age_range: "Age Range",
    city: "City",
    max_distance: "Max. distance",
    select_language: "Select language",
    select_orientation: 'Select orientation',
    save: "Save",
    reset_filters: "Reset Filters",
    erotic_image: "Erotic Image",
    only_for_friends: 'Only for friends',
    unlock_for: "Unlock for",
    report: "Report",
    block: "Block",
    interests: "Interests",
    details: "Details",
    dob: "Date of birth",
    friend_request: "Friend request",
    like: "Like",
    kiss: "Kiss",
    sticker: "Sticker",
    cost: "Cost",
    Coins: "Coins",
    send: "Send",
    cancel: "Cancel",
    notifications: "Notifications",
    no_notifications_found: "No notifications found!",
    friend_requests: "Friend requests",
    you_have_sent_friend_request_to: "You have sent friend request to",
    no_chats_found: "No chats found!",
    messages: "Messages",
    type_message: "Type message",
    send_message_for: "Send message for",
    view_profile: "View profile",
    deleteconversation: "Delete Conversation",
    deletealert: "Are you sure you want to delete this?",
    this: "this",
    conversation: "conversation",
    delete: "Delete",
    step: "Step",
    payment_method: "Payment method",
    choose_your_package_size: "Choose your package size",
    own_package: "Own package",
    own_package_description: "How many credits would you like to have? - Here you have it in your own hands!",
    order_now: "Order now",
    no_friends: 'No friends found!',
    kisses: 'Kisses',
    logout: 'Logout',
    profile: "Profile",
    boost: "Boost",
    photos: 'Photos',
    account_info: "Account Info",
    appearance: "Appearance",
    language: "Language",
    privacy_policy: 'Privacy Policy',
    help: "Help",
    support: "Support",
}

const DUTCH_STRINGS = {
    find_your_match: "Vind uw match met onze krachtige algoritmen",
    casual_chating: "Casual chatten en flirten",
    login: "Log in",
    register: 'Registreren',
    email: 'E-mail',
    email_error_1: 'Voer uw e-mailadres in!',
    email_error_2: 'Ongeldig e-mailadres!',
    password: 'Wachtwoord',
    confirm_password: 'bevestig wachtwoord',
    password_error_1: 'Voer wachtwoord in alstublieft!',
    password_error_2: "Wachtwoord komt niet overeen!",
    forgot_password: 'Wachtwoord vergeten?',
    or: "of",
    login_with_facebook: "Log in met Facebook",
    login_with_google: "Log in met Google",
    login_with_apple: "Log in met Apple",
    continue_with_facebook: "Ga verder met Facebook",
    continue_with_google: "Ga verder met Google",
    continue_with_apple: "Ga verder met Apple",
    dont_have_an_account: "Heb je geen account?",
    create_one: 'Creëer er een',
    back: "Terug",
    forgot_password_title: "Bent u uw wachtwoord vergeten?",
    forgot_password_description: "Voer hieronder uw e-mailadres in dat u gebruikt voor uw account en we sturen u een link voor het opnieuw instellen van uw wachtwoord.",
    request_new_password: "Vraag nieuw wachtwoord aan",
    back_to_login: "Terug naar Inloggen",
    create_account: "Maak account",
    i_am: 'ik ben',
    next: 'De volgende',
    user_name: 'Gebruikersnaam',
    user_name_error_1: 'Gebruikersnaam mag niet leeg zijn!',
    birthday: "Verjaardag",
    gender: 'Geslacht',
    optional: "Optioneel",
    passions: "Passies",
    add_passions: "Passies toevoegen",
    sexual_orientation: "Seksuele geaardheid",
    add_sexual_orientation: "Voeg seksuele geaardheid toe",
    continue: "Doorgaan met",
    select_profile_picture: "Selecteer profielfoto",
    flirts: 'Flirt',
    spotlight: "Spotlight",
    filter_flirt_suggestions: "Filter flirt-suggesties",
    i_am_looking_for: "ik zoek",
    select_gender: "Selecteer geslacht",
    age_range: "Leeftijdscategorie",
    city: "stad",
    max_distance: "Max. Hoogte afstand",
    select_language: "Selecteer taal",
    select_orientation: 'Selecteer oriëntatie',
    save: "Sparen",
    reset_filters: "Filters resetten",
    erotic_image: "Erotisch beeld",
    only_for_friends: 'Alleen voor vrienden',
    unlock_for: "Ontgrendel voor",
    report: "Verslag doen van",
    block: "Blok",
    interests: "Interesses",
    details: "Details",
    dob: "Geboortedatum",
    friend_request: "Vriendschapsverzoek",
    like: "Leuk vinden",
    kiss: "Kus",
    sticker: "Sticker",
    cost: "Kosten",
    Coins: "Munten",
    send: "Sturen",
    cancel: "annuleren",
    notifications: "Meldingen",
    no_notifications_found: "Geen notificaties gevonden!",
    friend_requests: "Vriendschapsverzoeken",
    you_have_sent_friend_request_to: "Je hebt een vriendschapsverzoek gestuurd naar",
    no_chats_found: "Geen chats gevonden!",
    messages: "Berichten",
    type_message: "Typ bericht",
    send_message_for: "Stuur bericht voor",
    view_profile: "Bekijk profiel",
    deleteconversation: "Verwijder gesprek",
    deletealert: "Weet u zeker dat u dit wilt verwijderen?",
    this: "dit",
    conversation: "gesprek",
    delete: "Verwijderen",
    step: "Stap",
    payment_method: "Betalingswijze",
    choose_your_package_size: "Kies uw pakketgrootte",
    own_package: "Eigen pakket",
    own_package_description: "Hoeveel credits zou je willen hebben? - Hier heb je het in eigen handen!",
    order_now: "Bestel nu",
    no_friends: 'Geen vrienden gevonden!',
    kisses: 'Kusjes',
    logout: 'Uitloggen',
    profile: "Profiel",
    boost: "Boost",
    photos: "Foto's",
    account_info: "Account informatie",
    appearance: "Uiterlijk",
    language: "Taal",
    privacy_policy: 'Privacybeleid',
    help: "Helpen",
    support: "Ondersteuning",
}

const SPANISH_STRINGS = {
    find_your_match: "Encuentra tu pareja con nuestros potentes algoritmos",
    casual_chating: "Charlar y coquetear casualmente",
    login: "Acceso",
    register: 'Registrarse',
    email: "Correo electrónico",
    email_error_1: "Por favor ingrese la dirección de correo electrónico.",
    email_error_2: 'Dirección de correo electrónico inválida.',
    password: 'Contraseña',
    confirm_password: 'confirmar Contraseña',
    password_error_1: '¡Por favor, ingrese contraseña!',
    password_error_2: "¡La contraseña no coincide!",
    forgot_password: '¿Se te olvidó tu contraseña?',
    or: "o",
    login_with_facebook: "Iniciar sesión con Facebook",
    login_with_google: "Iniciar sesión con Google",
    login_with_apple: "Iniciar sesión con Apple",
    continue_with_facebook: "Continuar con Facebook",
    continue_with_google: "Continuar con Google",
    continue_with_apple: "Continuar con Apple",
    dont_have_an_account: "¿No tienes una cuenta?",
    create_one: 'Crea uno',
    back: "atrás",
    forgot_password_title: "¿Olvidaste tu contraseña?",
    forgot_password_description: "Ingrese la dirección de correo electrónico que está utilizando para su cuenta a continuación y le enviaremos un enlace para restablecer la contraseña.",
    request_new_password: "Pide nueva contraseña",
    back_to_login: "Atrás para iniciar sesión",
    create_account: "Crear una cuenta",
    i_am: 'estoy',
    next: 'Próxima',
    user_name: 'Nombre de usuario',
    user_name_error_1: '¡El nombre de usuario no debe estar vacío',
    birthday: "Cumpleaños",
    gender: 'Género',
    optional: "Opcional",
    passions: "Pasiones",
    add_passions: "Agrega pasiones",
    sexual_orientation: "Orientación sexual",
    add_sexual_orientation: "Agregar orientación sexual",
    continue: "Continuar",
    select_profile_picture: "Seleccionar foto de perfil",
    flirts: 'Coquetea',
    spotlight: "Destacar",
    filter_flirt_suggestions: "Filtrar sugerencias de coqueteo",
    i_am_looking_for: "Estoy buscando",
    select_gender: "Seleccione género",
    age_range: "Rango de edad",
    city: "Ciudad",
    max_distance: "Max. distancia",
    select_language: "Seleccione el idioma",
    select_orientation: 'Seleccionar orientación',
    save: "Ahorrar",
    reset_filters: "Restablecer filtros",
    erotic_image: "Imagen erótica",
    only_for_friends: 'Solo para amigas',
    unlock_for: "Desbloquear para",
    report: "Informe",
    block: "Cuadra",
    interests: "Intereses",
    details: "Detalles",
    dob: "Fecha de nacimiento",
    friend_request: "Solicitud de amistad",
    like: "Como",
    kiss: "Beso",
    sticker: "Pegatina",
    cost: "Costo",
    Coins: "Monedas",
    send: "Enviar",
    cancel: "Cancelar",
    notifications: "Notificaciones",
    no_notifications_found: "¡No se encontraron notificaciones!",
    friend_requests: "Peticiones de amistad",
    you_have_sent_friend_request_to: "Has enviado una solicitud de amistad a",
    no_chats_found: "¡No se encontraron chats!",
    messages: "Mensajes",
    type_message: "Escribir mensaje",
    send_message_for: "Enviar mensaje para",
    view_profile: "Ver perfil",
    deleteconversation: "Eliminar la conversación",
    deletealert: "¿Estás segura de que quieres eliminar esto?",
    this: "esta",
    conversation: "conversacion",
    delete: "Borrar",
    step: "Paso",
    payment_method: "Método de pago",
    choose_your_package_size: "Elija el tamaño de su paquete",
    own_package: "Paquete propio",
    own_package_description: "¿Cuántos créditos le gustaría tener? - ¡Aquí lo tienes en tus propias manos!",
    order_now: "Ordenar ahora",
    no_friends: '¡No se encontraron amigos!',
    kisses: 'Besos',
    logout: 'Cerrar sesión',
    profile: "Perfil",
    boost: "Aumentar",
    photos: 'Fotos',
    account_info: "Informacion de cuenta",
    appearance: "Apariencia",
    language: "Idioma",
    privacy_policy: 'Política de privacidad',
    help: "Ayudar",
    support: "Apoyo",
}

const FRENCH_STRINGS = {
    find_your_match: "Trouvez votre match avec nos algorithmes puissants",
    casual_chating: "Bavarder et flirter occasionnellement",
    login: "Connexion",
    register: "S'inscrire",
    email: 'E-mail',
    email_error_1: 'Veuillez saisir votre adresse e-mail!',
    email_error_2: 'Adresse e-mail invalide!',
    password: 'Mot de passe',
    confirm_password: 'Confirmez le mot de passe',
    password_error_1: 'Veuillez entrer le mot de passe!',
    password_error_2: "Le mot de passe ne correspond pas!",
    forgot_password: 'Mot de passe oublié?',
    or: "ou alors",
    login_with_facebook: "Connectez-vous avec Facebook",
    login_with_google: "Connectez-vous avec Google",
    login_with_apple: "Connectez-vous avec Apple",
    continue_with_facebook: "Continuez avec Facebook",
    continue_with_google: "Continuer avec Google",
    continue_with_apple: "Continuer avec Apple",
    dont_have_an_account: "Tu n'as pas de compte?",
    create_one: 'Créer une',
    back: "Dos",
    forgot_password_title: "Avez-vous oublié votre mot de passe?",
    forgot_password_description: "Veuillez entrer votre adresse e-mail que vous utilisez pour votre compte ci-dessous et nous vous enverrons un lien de réinitialisation de mot de passe.",
    request_new_password: "Demander un nouveau mot de passe",
    back_to_login: "Retour connexion",
    create_account: "Créer un compte",
    i_am: 'Je suis',
    next: 'Suivante',
    user_name: "Nom d'utilisateur",
    user_name_error_1: "Le nom d'utilisateur ne doit pas être vide!",
    birthday: "Date d'anniversaire",
    gender: 'Genre',
    optional: "Optionnelle",
    passions: "Passions",
    add_passions: "Ajouter des passions",
    sexual_orientation: "Orientation sexuelle",
    add_sexual_orientation: "Ajouter une orientation sexuelle",
    continue: "Continuer",
    select_profile_picture: "Sélectionnez une photo de profil",
    flirts: 'Flirter',
    spotlight: "Projecteur",
    filter_flirt_suggestions: "Filtrer les suggestions de flirt",
    i_am_looking_for: "Je recherche",
    select_gender: "Sélectionnez le sexe",
    age_range: "Tranche d'âge",
    city: "Ville",
    max_distance: "Max. distance",
    select_language: "Choisir la langue",
    select_orientation: "Sélectionnez l'orientation",
    save: "Sauvegarder",
    reset_filters: "Réinitialiser les filtres",
    erotic_image: "Image érotique",
    only_for_friends: 'Seulement pour les amis',
    unlock_for: "Déverrouiller pour",
    report: "Signaler",
    block: "Bloquer",
    interests: "Intérêts",
    details: "Des détails",
    dob: "Date de naissance",
    friend_request: "Demande d'ami",
    like: "Comme",
    kiss: "Embrasser",
    sticker: "Autocollant",
    cost: "Coût",
    Coins: "Pièces de monnaie",
    send: "Envoyer",
    cancel: "Annuler",
    notifications: "Notifications",
    no_notifications_found: "Aucune notification trouvée!",
    friend_requests: "Demandes d'ami",
    you_have_sent_friend_request_to: "Vous avez envoyé une demande d'ami à",
    no_chats_found: "Aucun chat trouvé!",
    messages: "messages",
    type_message: "Tapez le message",
    send_message_for: "Envoyer un message pour",
    view_profile: "Voir le profil",
    deleteconversation: "Supprimer la conversation",
    deletealert: "Voulez-vous vraiment le supprimer?",
    this: "cette",
    conversation: "conversation",
    delete: "Effacer",
    step: "Marcher",
    payment_method: "Mode de paiement",
    choose_your_package_size: "Choisissez la taille de votre colis",
    own_package: "Propre paquet",
    own_package_description: "Combien de crédits aimeriez-vous avoir? - Ici, vous l'avez entre vos mains!",
    order_now: "Commandez maintenant",
    no_friends: 'Aucun ami trouvé!',
    kisses: 'Baisers',
    logout: 'Se déconnecter',
    profile: "Profil",
    boost: "Renforcer",
    photos: 'Photos',
    account_info: "Informations de compte",
    appearance: "Apparence",
    language: "Langue",
    privacy_policy: "Politique de confidentialité",
    help: "Aider",
    support: "Support",
}